# Generated by Django 4.0.4 on 2022-05-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='berry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='berries', to='cakes.cakeberry', verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decors', to='cakes.cakedecor', verbose_name='Декор'),
        ),
    ]
