# Generated by Django 4.0.4 on 2022-04-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deliver_date',
            new_name='delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_comments',
            field=models.TextField(blank=True, verbose_name='Комментарий для курьера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'Неоплачен'), ('pay', 'Оплачен'), ('a', 'Принят'), ('p', 'Готовится'), ('d', 'Передан в доставку'), ('c', 'Выполнен')], default='n', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
