# Generated by Django 4.0.4 on 2022-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'Новый'), ('a', 'Принят'), ('p', 'Готовится'), ('d', 'Передан в доставку'), ('c', 'Выполнен')], default='s', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
