# Generated by Django 4.0.4 on 2022-04-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_cakeberry_cakedecor_cakelevel_cakeshape_caketopping_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cakeberry',
            options={'verbose_name': 'Ягода', 'verbose_name_plural': 'Ягоды'},
        ),
        migrations.AlterModelOptions(
            name='cakedecor',
            options={'verbose_name': 'Декор', 'verbose_name_plural': 'Декор'},
        ),
        migrations.AlterModelOptions(
            name='cakelevel',
            options={'verbose_name': 'Уровень торта', 'verbose_name_plural': 'Уровни торта'},
        ),
        migrations.AlterModelOptions(
            name='cakeshape',
            options={'verbose_name': 'Форма торта', 'verbose_name_plural': 'Формы торта'},
        ),
        migrations.AlterModelOptions(
            name='caketopping',
            options={'verbose_name': 'Топпинг', 'verbose_name_plural': 'Топпинги'},
        ),
        migrations.RemoveField(
            model_name='cake',
            name='level_count',
        ),
        migrations.AddField(
            model_name='cake',
            name='level_count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='cakes.cakelevel', verbose_name='Количество уровней торта'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cake',
            name='shape',
        ),
        migrations.AddField(
            model_name='cake',
            name='shape',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='cakes.cakeshape', verbose_name='Форма торта'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cake',
            name='topping',
        ),
        migrations.AddField(
            model_name='cake',
            name='topping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='cakes.caketopping', verbose_name='Топпинг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caketopping',
            name='cake_topping',
            field=models.CharField(blank=True, choices=[(None, 'Выберите топпинг'), ('white', 'Белый соус'), ('caramel', 'Карамельный'), ('maple', 'Кленовый'), ('blueberry', 'Черничный'), ('choco', 'Молочный шоколад'), ('strawberry', 'Клубничный')], max_length=15, verbose_name='Топпинг'),
        ),
    ]
