# Generated by Django 4.0.4 on 2022-04-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий для курьера'),
        ),
    ]
