# Generated by Django 4.0.4 on 2022-04-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='firstname',
            field=models.CharField(default=1, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default=1, max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время регистрации заказа')),
                ('called_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время звонка клиенту')),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время доставки заказа')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='cakes.cake', verbose_name='Заказанный торт')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='cakes.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-registered_at'],
            },
        ),
    ]
