# Generated by Django 4.0.4 on 2022-04-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0006_alter_cakedecor_cake_decor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='base_price',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=15, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
