# Generated by Django 4.0.4 on 2022-04-28 12:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0007_remove_cake_base_price_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='berry',
        ),
        migrations.AddField(
            model_name='cake',
            name='berry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='berries', to='cakes.cakeberry', verbose_name='Ягоды'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cake',
            name='decor',
        ),
        migrations.AddField(
            model_name='cake',
            name='decor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='decors', to='cakes.cakedecor', verbose_name='Декор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cakeberry',
            name='cake_berry',
            field=models.CharField(max_length=15, verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='cakedecor',
            name='cake_decor',
            field=models.CharField(max_length=15, verbose_name='Декор'),
        ),
        migrations.AlterField(
            model_name='cakelevel',
            name='level_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество уровней'),
        ),
        migrations.AlterField(
            model_name='cakeshape',
            name='shape',
            field=models.CharField(max_length=50, verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='caketopping',
            name='cake_topping',
            field=models.CharField(max_length=50, verbose_name='Топпинг'),
        ),
    ]
