# Generated by Django 4.0.4 on 2022-04-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0008_remove_cake_berry_cake_berry_remove_cake_decor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakelevel',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
    ]
